[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.11"
name = "mcp_linux_ssh"
dependencies = [
    "mcp[cli]",
]
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
mcp-linux-ssh = "mcp_linux_ssh:server.main"
